/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * DemoPanel2.java
 *
 * Created on 14.09.2009, 15:01:16
 */
package de.cismet.cismap.navigatorplugin.options;

import de.cismet.lookupoptions.*;

import de.cismet.lookupoptions.options.GeneralOptionsCategory;

/**
 * example.
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
//@ServiceProvider(service = OptionsPanelController.class)
public class TestPanel extends AbstractOptionsPanel implements OptionsPanelController {

    //~ Static fields/initializers ---------------------------------------------

    /** Use serialVersionUID for interoperability. */
    private static final long serialVersionUID = -6809355623503098744L;

    private static final String OPTION_NAME = "Beispiel 1"; // NOI18N

    //~ Instance fields --------------------------------------------------------

    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form DemoPanel2.
     */
    public TestPanel() {
        super(OPTION_NAME, GeneralOptionsCategory.class);
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    @Override
    public int getOrder() {
        return 2;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText(org.openide.util.NbBundle.getMessage(TestPanel.class, "TestPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

        jButton2.setText(org.openide.util.NbBundle.getMessage(TestPanel.class, "TestPanel.jButton2.text")); // NOI18N

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jButton1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                415,
                Short.MAX_VALUE).addGroup(
                layout.createSequentialGroup().addGap(90, 90, 90).addComponent(
                    jButton2,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    233,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(92, Short.MAX_VALUE)));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap().addComponent(
                    jButton2,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    109,
                    Short.MAX_VALUE).addGap(35, 35, 35).addComponent(
                    jButton1,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    69,
                    javax.swing.GroupLayout.PREFERRED_SIZE)));
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
        try {
            int count;
            try {
                count = Integer.valueOf(jButton2.getText());
            } catch (NumberFormatException ex) {
                count = 0;
            }
            count++;
            jButton2.setText(Integer.toString(count));
            jButton2.setToolTipText(
                "<html><img src=\"http://www.drweb.de/icons/twitter/pd_twitter_iconset/pd_twitter_iconset/PNG/256/icon_a.png\" alt=\""
                        + Integer.toString(count)
                        + "\"/></html>");                                        // NOI18N
        } catch (Throwable t) {
            if (log.isDebugEnabled()) {
                log.debug("Throwable", t);                                       // NOI18N
            }
        }
    }                                                                            //GEN-LAST:event_jButton1ActionPerformed
}
