/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cismap.navigatorplugin;

import com.vividsolutions.jts.geom.Point;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import de.cismet.cismap.commons.BoundingBox;
import de.cismet.cismap.commons.CrsTransformer;
import de.cismet.cismap.commons.gui.MappingComponent;
import de.cismet.cismap.commons.gui.piccolo.FixedPImage;
import de.cismet.cismap.commons.interaction.CismapBroker;

import de.cismet.tools.StaticDecimalTools;

import de.cismet.tools.gui.StaticSwingTools;

/**
 * DOCUMENT ME!
 *
 * @author   gbaatz
 * @version  $Revision$, $Date$
 */
public class GotoPointDialog extends javax.swing.JDialog {

    //~ Instance fields --------------------------------------------------------

    private MappingComponent mapC;
    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());
    private ImageIcon mark = new javax.swing.ImageIcon(getClass().getResource(
                "/de/cismet/cismap/commons/gui/res/markPoint.png")); // NOI18N
    private FixedPImage pMark = new FixedPImage(mark.getImage());

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPosition;
    private javax.swing.JCheckBox cbMarkPoint;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField tfCoordinates;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form GotoPointDialog.
     *
     * @param  mapC   DOCUMENT ME!
     * @param  modal  DOCUMENT ME!
     */
    public GotoPointDialog(final MappingComponent mapC, final boolean modal) {
        super(StaticSwingTools.getParentFrame(mapC), modal);
        this.mapC = mapC;
        initComponents();
        lblIcon.setIcon(mark);
        initTfCoordinatesText();
        setLocationRelativeTo(StaticSwingTools.getParentFrame(mapC));
        setVisible(true);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        tfCoordinates = new javax.swing.JTextField();
        btnPosition = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbMarkPoint = new javax.swing.JCheckBox();
        lblMessage = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfCoordinates.setText(org.openide.util.NbBundle.getMessage(
                GotoPointDialog.class,
                "GotoPointDialog.tfCoordinates.text")); // NOI18N

        btnPosition.setText(org.openide.util.NbBundle.getMessage(
                GotoPointDialog.class,
                "GotoPointDialog.btnPosition.text")); // NOI18N
        btnPosition.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnPositionActionPerformed(evt);
                }
            });

        btnCancel.setText(org.openide.util.NbBundle.getMessage(
                GotoPointDialog.class,
                "GotoPointDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
                }
            });

        cbMarkPoint.setText(org.openide.util.NbBundle.getMessage(
                GotoPointDialog.class,
                "GotoPointDialog.cbMarkPoint.text")); // NOI18N

        lblMessage.setText(org.openide.util.NbBundle.getMessage(
                GotoPointDialog.class,
                "GotoPointDialog.lblMessage.text")); // NOI18N

        lblIcon.setText(org.openide.util.NbBundle.getMessage(GotoPointDialog.class, "GotoPointDialog.lblIcon.text")); // NOI18N

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGap(61, 61, 61).addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblMessage)
                                .addGroup(
                                    layout.createSequentialGroup().addComponent(btnPosition).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnCancel))
                                .addGroup(
                                    layout.createSequentialGroup().addComponent(
                                        tfCoordinates,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        263,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(
                                        cbMarkPoint).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                        lblIcon,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        19,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(
                    64,
                    Short.MAX_VALUE)));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(lblMessage).addGap(10, 10, 10).addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(
                        lblIcon,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE).addComponent(
                        cbMarkPoint,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE).addComponent(
                        tfCoordinates,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnPosition)
                                .addComponent(btnCancel)).addContainerGap(21, Short.MAX_VALUE)));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnPositionActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnPositionActionPerformed
        try {
            final String[] sa = tfCoordinates.getText().split(",");                 // NOI18N
            final Double gotoX = new Double(sa[0]);
            final Double gotoY = new Double(sa[1]);
            final BoundingBox bb = new BoundingBox(gotoX, gotoY, gotoX, gotoY);
            mapC.gotoBoundingBox(bb, true, false, mapC.getAnimationDuration());
            if (cbMarkPoint.isSelected()) {
                visualizePosition();
            }
        } catch (final Exception skip) {
            log.error("Error in mniGotoPointActionPerformed", skip);                // NOI18N
        } finally {
            setVisible(false);
        }
    }                                                                               //GEN-LAST:event_btnPositionActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnCancelActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }                                                                             //GEN-LAST:event_btnCancelActionPerformed

    /**
     * DOCUMENT ME!
     */
    private void initTfCoordinatesText() {
        final BoundingBox c = mapC.getCurrentBoundingBoxFromCamera();
        final double x = (c.getX1() + c.getX2()) / 2;
        final double y = (c.getY1() + c.getY2()) / 2;
        tfCoordinates.setText(StaticDecimalTools.round(x)
                    + "," // NOI18N
                    + StaticDecimalTools.round(y));
    }

    /**
     * DOCUMENT ME!
     */
    private void visualizePosition() {
        mapC.getHighlightingLayer().removeAllChildren();
        mapC.getHighlightingLayer().addChild(pMark);
        mapC.addStickyNode(pMark);
        final BoundingBox c = mapC.getCurrentBoundingBoxFromCamera();
        final double x = (c.getX1() + c.getX2()) / 2;
        final double y = (c.getY1() + c.getY2()) / 2;
        pMark.setOffset(x, y);
        pMark.setVisible(true);
        mapC.rescaleStickyNodes();

        // CismapBroker.getInstance().removeCrsChangeListener(this);
        // CismapBroker.getInstance().addCrsChangeListener(this);
    }
}
