/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cismap.navigatorplugin;

import Sirius.navigator.ui.ComponentRegistry;

import org.apache.commons.io.FilenameUtils;

import org.jdom.Element;

import java.awt.EventQueue;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;

import java.io.File;

import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileFilter;

import de.cismet.cismap.commons.BoundingBox;
import de.cismet.cismap.commons.RestrictedFileSystemView;
import de.cismet.cismap.commons.gui.ClipboardWaitDialog;
import de.cismet.cismap.commons.gui.MappingComponent;
import de.cismet.cismap.commons.interaction.CismapBroker;
import de.cismet.cismap.commons.tools.MapImageDownload;

import de.cismet.tools.configuration.Configurable;
import de.cismet.tools.configuration.NoWriteError;

import de.cismet.tools.gui.ConfirmationJFileChooser;
import de.cismet.tools.gui.StaticSwingTools;
import de.cismet.tools.gui.downloadmanager.DownloadManager;

import static javax.swing.Action.NAME;
import static javax.swing.Action.SMALL_ICON;

/**
 * DOCUMENT ME!
 *
 * @author   Gilles Baatz
 * @version  $Revision$, $Date$
 */
public class MapExportPanel extends javax.swing.JPanel implements Configurable {

    //~ Static fields/initializers ---------------------------------------------

    private static final ImageIcon clipboardIcon = new ImageIcon(MapExportPanel.class.getResource(
                "/images/clipboard.png"));
    private static final ImageIcon clipboardIcon16 = new ImageIcon(MapExportPanel.class.getResource(
                "/images/clipboard16.png"));
    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(GeoSearchButton.class);

    //~ Instance fields --------------------------------------------------------

    int httpInterfacePort = 9098;
    private ClipboardWaitDialog clipboarder;
    private MappingComponent mapC;
    private final ExportMapToClipboardAction exportMapToClipboardAction = new ExportMapToClipboardAction();
    private final ExportGeoPointToClipboardAction exportGeoPointToClipboardAction =
        new ExportGeoPointToClipboardAction();
    private final ExportMapToFileAction exportMapToFileAction = new ExportMapToFileAction();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.tools.gui.JPopupMenuButton btnClipboard;
    private javax.swing.ButtonGroup btngDpi;
    private javax.swing.ButtonGroup btngExportMap;
    private javax.swing.ButtonGroup btngFileFormat;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JRadioButtonMenuItem rmniExportMapClipboard;
    private javax.swing.JRadioButtonMenuItem rmniExportMapFile;
    private javax.swing.JRadioButtonMenuItem rmniGif;
    private javax.swing.JRadioButtonMenuItem rmniJpeg;
    private javax.swing.JRadioButtonMenuItem rmniPng;
    private javax.swing.JRadioButtonMenuItem rmniTif;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form MapExportPanel.
     */
    public MapExportPanel() {
        initComponents();
        try {
            final JFrame mainWindow = ComponentRegistry.getRegistry().getMainWindow();
            clipboarder = new ClipboardWaitDialog(mainWindow, true);
            mapC = CismapBroker.getInstance().getMappingComponent();
        } catch (Exception ex) {
            LOG.error("An exception occured in the constructor of MapExportPanel", ex);
        }
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPopupMenu1 = new javax.swing.JPopupMenu();
        rmniExportMapClipboard = new javax.swing.JRadioButtonMenuItem();
        rmniExportMapFile = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        rmniPng = new javax.swing.JRadioButtonMenuItem();
        rmniTif = new javax.swing.JRadioButtonMenuItem();
        rmniGif = new javax.swing.JRadioButtonMenuItem();
        rmniJpeg = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        btngExportMap = new javax.swing.ButtonGroup();
        btngFileFormat = new javax.swing.ButtonGroup();
        btngDpi = new javax.swing.ButtonGroup();
        btnClipboard = new de.cismet.tools.gui.JPopupMenuButton();

        rmniExportMapClipboard.setAction(exportMapToClipboardAction);
        btngExportMap.add(rmniExportMapClipboard);
        rmniExportMapClipboard.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(
            rmniExportMapClipboard,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.rmniExportMapClipboard.text")); // NOI18N
        jPopupMenu1.add(rmniExportMapClipboard);

        rmniExportMapFile.setAction(exportMapToFileAction);
        btngExportMap.add(rmniExportMapFile);
        org.openide.awt.Mnemonics.setLocalizedText(
            rmniExportMapFile,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.rmniExportMapFile.text")); // NOI18N
        jPopupMenu1.add(rmniExportMapFile);
        jPopupMenu1.add(jSeparator1);
        jPopupMenu1.add(jSeparator2);

        btngFileFormat.add(rmniPng);
        rmniPng.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(
            rmniPng,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.rmniPng.text")); // NOI18N
        jPopupMenu1.add(rmniPng);

        btngFileFormat.add(rmniTif);
        org.openide.awt.Mnemonics.setLocalizedText(
            rmniTif,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.rmniTif.text")); // NOI18N
        jPopupMenu1.add(rmniTif);

        btngFileFormat.add(rmniGif);
        org.openide.awt.Mnemonics.setLocalizedText(
            rmniGif,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.rmniGif.text")); // NOI18N
        jPopupMenu1.add(rmniGif);

        btngFileFormat.add(rmniJpeg);
        org.openide.awt.Mnemonics.setLocalizedText(
            rmniJpeg,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.rmniJpeg.text")); // NOI18N
        jPopupMenu1.add(rmniJpeg);
        jPopupMenu1.add(jSeparator3);

        jMenuItem3.setAction(exportGeoPointToClipboardAction);
        jPopupMenu1.add(jMenuItem3);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        btnClipboard.setAction(exportMapToClipboardAction);
        btnClipboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard.png")));    // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            btnClipboard,
            org.openide.util.NbBundle.getMessage(MapExportPanel.class, "MapExportPanel.btnClipboard.text")); // NOI18N
        btnClipboard.setToolTipText(org.openide.util.NbBundle.getMessage(
                MapExportPanel.class,
                "MapExportPanel.btnClipboard.toolTipText"));                                                 // NOI18N
        btnClipboard.setBorderPainted(false);
        btnClipboard.setContentAreaFilled(false);
        add(btnClipboard, java.awt.BorderLayout.CENTER);
    }                                                                                                        // </editor-fold>//GEN-END:initComponents

    @Override
    public void configure(final Element parent) {
//        LOG.fatal("MapExportPanel.configure: Not supported yet.", new Exception()); //NOI18N
//        return null;
    }

    @Override
    public void masterConfigure(final Element parent) {
        final Element prefs = parent.getChild("cismapPluginUIPreferences");               // NOI18N
        try {
            final Element httpInterfacePortElement = prefs.getChild("httpInterfacePort"); // NOI18N

            try {
                httpInterfacePort = new Integer(httpInterfacePortElement.getText());
            } catch (Throwable t) {
                LOG.warn("httpInterface was not configured. Set default value: " + httpInterfacePort, t); // NOI18N
            }
        } catch (Throwable t) {
            LOG.error("Error while loading the help urls (" + prefs.getChildren() + ")", t);              // NOI18N
        }
    }

    @Override
    public Element getConfiguration() throws NoWriteError {
        LOG.fatal("MapExportPanel.getConfiguration: Not supported yet.", new Exception()); // NOI18N
        return null;
    }

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private class ExportMapToClipboardAction extends AbstractAction {

        //~ Constructors -------------------------------------------------------

        /**
         * Creates a new ExportMapToClipboardAction object.
         */
        public ExportMapToClipboardAction() {
            putValue(NAME, "Aktuelles Kartenbild in Zwischenablage kopieren (Bitmap)");
            putValue(SMALL_ICON, clipboardIcon16);
        }

        //~ Methods ------------------------------------------------------------

        @Override
        public void actionPerformed(final ActionEvent e) {
            btnClipboard.setAction(this);

            final Thread t = new Thread(new Runnable() {

                        @Override
                        public void run() {
                            EventQueue.invokeLater(new Runnable() {

                                    @Override
                                    public void run() {
                                        StaticSwingTools.showDialog(clipboarder);
                                    }
                                });

                            final ImageSelection imgSel = new ImageSelection(mapC.getImage());
                            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(imgSel, null);
                            EventQueue.invokeLater(new Runnable() {

                                    @Override
                                    public void run() {
                                        clipboarder.dispose();
                                    }
                                });
                        }
                    });
            t.start();
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private class ExportMapToFileAction extends AbstractAction {

        //~ Constructors -------------------------------------------------------

        /**
         * Creates a new ExportMapToFileAction object.
         */
        public ExportMapToFileAction() {
            putValue(NAME, "Aktuelles Kartenbild in Datei kopieren");
            putValue(SMALL_ICON, clipboardIcon16);
        }

        //~ Methods ------------------------------------------------------------

        @Override
        public void actionPerformed(final ActionEvent e) {
            btnClipboard.setAction(this);
            final MappingComponent mappingComponent = CismapBroker.getInstance().getMappingComponent();

            final Image image = mappingComponent.getImage();
            final File file = chooseFile();

            if (file != null) {
                final String imageFilePath = file.getAbsolutePath();
                final MapImageDownload imageDownload = new MapImageDownload(
                        FilenameUtils.getBaseName(imageFilePath),
                        FilenameUtils.getExtension(imageFilePath),
                        file,
                        mappingComponent);
                DownloadManager.instance().add(imageDownload);
            }
        }

        /**
         * Opens a JFileChooser with a filter for jpegs and checks if the chosen file has the right extension. If not
         * the right extension is added, therefor the extension of a file returned by this method is always .jpg or
         * .jpeg
         *
         * @return  DOCUMENT ME!
         */
        private File chooseFile() {
            JFileChooser fc;
            try {
                fc = new ConfirmationJFileChooser(DownloadManager.instance().getDestinationDirectory());
            } catch (Exception bug) {
                // Bug Workaround http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6544857
                fc = new JFileChooser(DownloadManager.instance().getDestinationDirectory(),
                        new RestrictedFileSystemView());
            }

            fc.setAcceptAllFileFilterUsed(false);
            fc.setFileFilter(new FileFilter() {

                    @Override
                    public boolean accept(final File f) {
                        return f.isDirectory()
                                    || f.getName().toLowerCase().endsWith(".jpg")
                                    || f.getName().toLowerCase().endsWith(".jpeg"); // NOI18N
                    }

                    @Override
                    public String getDescription() {
                        return org.openide.util.NbBundle.getMessage(
                                CismapPlugin.class,
                                "CismapPlugin.save.FileFilter.getDescription.return"); // NOI18N
                    }
                });

            final int state = fc.showSaveDialog(MapExportPanel.this);
            if (LOG.isDebugEnabled()) {
                LOG.debug("state:" + state); // NOI18N
            }

            if (state == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                final String name = file.getAbsolutePath();

                if (!(name.endsWith(".jpg") || name.endsWith(".jpeg"))) { // NOI18N
                    file = new File(file.getAbsolutePath() + ".jpg");
                }
                return file;
            } else {
                return null;
            }
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private class ExportGeoPointToClipboardAction extends AbstractAction {

        //~ Constructors -------------------------------------------------------

        /**
         * Creates a new ExportGeoPointToClipboardAction object.
         */
        public ExportGeoPointToClipboardAction() {
            putValue(NAME, "Aktueller Punkt in Zwischenablage kopieren");
            putValue(SMALL_ICON, clipboardIcon16);
        }

        //~ Methods ------------------------------------------------------------

        @Override
        public void actionPerformed(final ActionEvent e) {
            btnClipboard.setAction(this);
            final Thread t = new Thread(new Runnable() {

                        @Override
                        public void run() {
                            final BoundingBox bb = mapC.getCurrentBoundingBoxFromCamera();
                            final String u = "http://localhost:" + httpInterfacePort + "/gotoBoundingBox?x1="
                                        + bb.getX1()                                                       // NOI18N
                                        + "&y1=" + bb.getY1() + "&x2=" + bb.getX2() + "&y2=" + bb.getY2(); // NOI18N
                            final GeoLinkUrl url = new GeoLinkUrl(u);
                            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(url, null);
                            EventQueue.invokeLater(new Runnable() {

                                    @Override
                                    public void run() {
                                        clipboarder.dispose();
                                    }
                                });
                        }
                    });
            t.start();
        }
    }
}
