/*
 * test.java
 *
 * Created on 14. Februar 2006, 16:20
 */

package de.cismet.cismap.navigatorplugin;



import de.cismet.tools.gui.JXCollapsiblePane;
import java.awt.BorderLayout;
import javax.swing.JButton;
//import org.jdesktop.swingx.JXCollapsiblePane1;



/**
 *
 * @author  thorsten.hell@cismet.de
 */
public class test extends javax.swing.JFrame {
    JXCollapsiblePane jXCollapsiblePane1=new JXCollapsiblePane();
    JXCollapsiblePane jXCollapsiblePane2=new JXCollapsiblePane();
    /** Creates new form test */
    public test() {
        initComponents();
        //getContentPane().add(jXCollapsiblePane1,BorderLayout.EAST);
         this.jXCollapsiblePane1.setOrientation(de.cismet.tools.gui.JXCollapsiblePane.HORIZONTAL_ORIENTATION);
        this.jXCollapsiblePane1.setLayout(new BorderLayout());
        jSplitPane1.setRightComponent(jXCollapsiblePane1);
        jXCollapsiblePane1.add(new JButton("klgsyhsykh"),BorderLayout.CENTER);
        //getContentPane().add(jXCollapsiblePane2,BorderLayout.NORTH);

//       
//        this.jXCollapsiblePane1.add(new JButton("KJKHJKKJKJKH"),BorderLayout.CENTER);
//        this.jXCollapsiblePane2.setLayout(new BorderLayout());
//        this.jXCollapsiblePane2.setOrientation(de.cismet.tools.gui.JXCollapsiblePane.VERTICAL_ORIENTATION);
//        this.jXCollapsiblePane2.add(new JButton("ALT"),BorderLayout.CENTER);
//        CapabilityWidget cw=new CapabilityWidget();
//        LayerWidget lc=new LayerWidget();
//        JPanel p=new JPanel();
//        DockingManager.registerDockable(cw, "LALA", true);
//        DockingManager.registerDockable(lc, "LALA2", true);
//        //defaultDockingPort1.add(cw);
//        defaultDockingPort1.dock(cw, "NUPSI", DockingPort.EAST_REGION, false);
//        defaultDockingPort1.dock(lc, "NUPSI2", DockingPort.SOUTH_REGION, false);
//        defaultDockingPort1.dock(p, "NUPSI3", DockingPort.CENTER_REGION, false);
//        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.NORTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jXCollapsiblePane1.setCollapsed(!jXCollapsiblePane1.isCollapsed());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    

    
}