/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cismap.navigatorplugin.protocol;

import com.vividsolutions.jts.geom.Geometry;

import java.awt.Component;

import de.cismet.commons.gui.protocol.AbstractProtocolStepPanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class GeoContextProtocolStepPanel extends AbstractProtocolStepPanel<GeoContextProtocolStep> {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cismap.navigatorplugin.protocol.GeometryProtocolStepPanel geometryProtocolStepPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new GeoContextProtocolStepPanel object.
     */
    public GeoContextProtocolStepPanel() {
        this(new GeoContextProtocolStepImpl((Geometry)null));
    }

    /**
     * Creates new form GeoContextProtocolStepPanel.
     *
     * @param  geoContextProtocolStep  DOCUMENT ME!
     */
    public GeoContextProtocolStepPanel(final GeoContextProtocolStep geoContextProtocolStep) {
        super(geoContextProtocolStep);
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        final java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        geometryProtocolStepPanel1 = new de.cismet.cismap.navigatorplugin.protocol.GeometryProtocolStepPanel(
                ((GeoContextProtocolStepImpl)getProtocolStep()).getGeometryProtocolStep(),
                false);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblTitle,
            org.openide.util.NbBundle.getMessage(
                GeoContextProtocolStepPanel.class,
                "GeoContextProtocolStepPanel.lblTitle.text")); // NOI18N

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sirius/navigator/resource/img/map.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            lblIcon,
            org.openide.util.NbBundle.getMessage(
                GeoContextProtocolStepPanel.class,
                "GeoContextProtocolStepPanel.lblIcon.text"));                                                         // NOI18N

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(geometryProtocolStepPanel1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    @Override
    public Component getIconComponent() {
        return lblIcon;
    }

    @Override
    public Component getTitleComponent() {
        return lblTitle;
    }
}
