/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cismap.navigatorplugin.protocol;

import Sirius.navigator.search.CidsServerSearchMetaObjectNodeWrapper;

import Sirius.server.middleware.types.MetaObjectNode;

import java.awt.Component;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;

import de.cismet.commons.gui.protocol.AbstractProtocolStepPanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class MetaSearchProtocolStepPanel extends AbstractProtocolStepPanel<MetaSearchProtocolStep> {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sirius.navigator.search.CidsServerSearchProtocolStepPanel cidsServerSearchProtocolStepPanel1;
    private de.cismet.cismap.navigatorplugin.protocol.GeomSearchProtocolStepPanel geomSearchProtocolStepPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private javax.swing.JLabel lblIconNone;
    private javax.swing.JLabel lblTitle;
    private de.cismet.cismap.navigatorplugin.protocol.MetaObjectNodeTree metaSearchProtocolStepPanelSearchObjectsTree1;
    private de.cismet.cismap.navigatorplugin.protocol.SearchTopicsProtocolStepPanel searchTopicsProtocolStepPanel1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new GeoSearchProtocolStepPanel object.
     */
    public MetaSearchProtocolStepPanel() {
        this(new MetaSearchProtocolStepImpl(
                "",
                "",
                new HashSet<MetaSearchProtocolStepSearchTopic>(),
                new ArrayList<CidsServerSearchMetaObjectNodeWrapper>(),
                new ArrayList<CidsServerSearchMetaObjectNodeWrapper>()));
    }

    /**
     * Creates new form MetaSearchProtocolStepPanel.
     *
     * @param  geoSearchProtocolStep  DOCUMENT ME!
     */
    public MetaSearchProtocolStepPanel(final MetaSearchProtocolStep geoSearchProtocolStep) {
        super(geoSearchProtocolStep);
        initComponents();

        setSearchObjectsPanelVisible(false);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private Collection<MetaObjectNode> getSearchObjectNodesList() {
        if (getProtocolStep() != null) {
            final Collection<MetaObjectNode> searchObjectNodes = ((MetaSearchProtocolStep)getProtocolStep())
                        .getSearchObjectNodes();
            if (searchObjectNodes != null) {
                return searchObjectNodes;
            }
        }
        return new ArrayList<MetaObjectNode>();
    }

    @Override
    public Component getIconComponent() {
        return lblIconNone;
    }

    @Override
    public Component getTitleComponent() {
        return lblTitle;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblIconNone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cidsServerSearchProtocolStepPanel1 = new Sirius.navigator.search.CidsServerSearchProtocolStepPanel(
                getProtocolStep());
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        try {
            metaSearchProtocolStepPanelSearchObjectsTree1 =
                new de.cismet.cismap.navigatorplugin.protocol.MetaObjectNodeTree();
        } catch (java.lang.Exception e1) {
            e1.printStackTrace();
        }
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        searchTopicsProtocolStepPanel1 = new de.cismet.cismap.navigatorplugin.protocol.SearchTopicsProtocolStepPanel(
                getProtocolStep());
        geomSearchProtocolStepPanel1 = new de.cismet.cismap.navigatorplugin.protocol.GeomSearchProtocolStepPanel(
                getProtocolStep());

        lblIconNone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pluginSearch.gif"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            lblIconNone,
            org.openide.util.NbBundle.getMessage(
                MetaSearchProtocolStepPanel.class,
                "MetaSearchProtocolStepPanel.lblIconNone.text"));                                           // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel2,
            org.openide.util.NbBundle.getMessage(
                MetaSearchProtocolStepPanel.class,
                "MetaSearchProtocolStepPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel3,
            org.openide.util.NbBundle.getMessage(
                MetaSearchProtocolStepPanel.class,
                "MetaSearchProtocolStepPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel4,
            org.openide.util.NbBundle.getMessage(
                MetaSearchProtocolStepPanel.class,
                "MetaSearchProtocolStepPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            lblTitle,
            org.openide.util.NbBundle.getMessage(
                MetaSearchProtocolStepPanel.class,
                "MetaSearchProtocolStepPanel.lblTitle.text")); // NOI18N

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cidsServerSearchProtocolStepPanel1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        metaSearchProtocolStepPanelSearchObjectsTree1.setResultNodes(getSearchObjectNodesList().toArray(
                new MetaObjectNode[0]));
        jScrollPane2.setViewportView(metaSearchProtocolStepPanelSearchObjectsTree1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jXHyperlink1,
            org.openide.util.NbBundle.getMessage(
                MetaSearchProtocolStepPanel.class,
                "MetaSearchProtocolStepPanel.jXHyperlink1.text")); // NOI18N
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jXHyperlink1ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jXHyperlink1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(searchTopicsProtocolStepPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(geomSearchProtocolStepPanel1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jXHyperlink1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jXHyperlink1ActionPerformed
        toggleSearchObjectsPanelVisibility();
    }                                                                                //GEN-LAST:event_jXHyperlink1ActionPerformed

    /**
     * DOCUMENT ME!
     */
    private void toggleSearchObjectsPanelVisibility() {
        setSearchObjectsPanelVisible(!jPanel1.isVisible());
    }

    /**
     * DOCUMENT ME!
     *
     * @param  visible  DOCUMENT ME!
     */
    private void setSearchObjectsPanelVisible(final boolean visible) {
        jPanel1.setVisible(visible);

        if ((getProtocolStep().getSearchObjectNodes() == null) || getProtocolStep().getSearchObjectNodes().isEmpty()) {
            jXHyperlink1.setVisible(false);
        } else {
            jXHyperlink1.setVisible(true);
            if (jPanel1.isVisible()) {
                jXHyperlink1.setText(Integer.toString(getProtocolStep().getSearchObjectNodes().size())
                            + " Suchobjekte verbergen");
            } else {
                jXHyperlink1.setText(Integer.toString(getProtocolStep().getSearchObjectNodes().size())
                            + " Suchobjekte anzeigen");
            }
        }

        revalidate();
    }
}
