/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cismap.navigatorplugin.protocol;

import java.awt.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;

import de.cismet.commons.gui.protocol.AbstractProtocolStepPanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class SearchTopicsProtocolStepPanel extends AbstractProtocolStepPanel<SearchTopicsProtocolStep> {

    //~ Static fields/initializers ---------------------------------------------

    private static final Map<String, ImageIcon> ICON_CACHE = new HashMap<String, ImageIcon>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private javax.swing.JLabel lblIconNone;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new SearchTopicsPanel object.
     */
    public SearchTopicsProtocolStepPanel() {
        this(null);
    }

    /**
     * Creates new form MetaSearchProtocolStepPanel.
     *
     * @param  searchTopicsProtocolStep  DOCUMENT ME!
     */
    public SearchTopicsProtocolStepPanel(final SearchTopicsProtocolStep searchTopicsProtocolStep) {
        super(searchTopicsProtocolStep);
        initComponents();

        setSearchTopicsPanelVisible(false);

        final List<MetaSearchProtocolStepSearchTopic> sortedTopics = new ArrayList<MetaSearchProtocolStepSearchTopic>();
        if (searchTopicsProtocolStep != null) {
            sortedTopics.addAll(searchTopicsProtocolStep.getSearchTopicInfos());
        }
        Collections.sort(sortedTopics, new Comparator<MetaSearchProtocolStepSearchTopic>() {

                @Override
                public int compare(final MetaSearchProtocolStepSearchTopic o1,
                        final MetaSearchProtocolStepSearchTopic o2) {
                    final String k1 = ((o1 == null) || (o1.getKey() == null)) ? "" : o1.getKey();
                    final String k2 = ((o2 == null) || (o2.getKey() == null)) ? "" : o2.getKey();
                    return k1.compareTo(k2);
                }
            });

        for (final MetaSearchProtocolStepSearchTopic topic : sortedTopics) {
            ((DefaultListModel<MetaSearchProtocolStepSearchTopic>)jList1.getModel()).addElement(topic);
        }
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblIconNone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();

        lblIconNone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pluginSearch.gif"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            lblIconNone,
            org.openide.util.NbBundle.getMessage(
                SearchTopicsProtocolStepPanel.class,
                "SearchTopicsProtocolStepPanel.lblIconNone.text"));                                         // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel2,
            org.openide.util.NbBundle.getMessage(
                SearchTopicsProtocolStepPanel.class,
                "SearchTopicsProtocolStepPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel3,
            org.openide.util.NbBundle.getMessage(
                SearchTopicsProtocolStepPanel.class,
                "SearchTopicsProtocolStepPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel4,
            org.openide.util.NbBundle.getMessage(
                SearchTopicsProtocolStepPanel.class,
                "SearchTopicsProtocolStepPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            lblTitle,
            org.openide.util.NbBundle.getMessage(
                SearchTopicsProtocolStepPanel.class,
                "SearchTopicsProtocolStepPanel.lblTitle.text")); // NOI18N

        setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jList1.setModel(
            new DefaultListModel<de.cismet.cismap.navigatorplugin.protocol.MetaSearchProtocolStepSearchTopic>());
        jList1.setCellRenderer(new TopicListCellRenderer());
        jScrollPane3.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jPanel2, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jXHyperlink2,
            org.openide.util.NbBundle.getMessage(
                SearchTopicsProtocolStepPanel.class,
                "SearchTopicsProtocolStepPanel.jXHyperlink2.text")); // NOI18N
        jXHyperlink2.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jXHyperlink2ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jXHyperlink2, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jXHyperlink2ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jXHyperlink2ActionPerformed
        toggleSearchTopicsPanelVisibility();
    }                                                                                //GEN-LAST:event_jXHyperlink2ActionPerformed

    /**
     * DOCUMENT ME!
     */
    private void toggleSearchTopicsPanelVisibility() {
        setSearchTopicsPanelVisible(!jPanel2.isVisible());
    }

    /**
     * DOCUMENT ME!
     *
     * @param  visible  DOCUMENT ME!
     */
    private void setSearchTopicsPanelVisible(final boolean visible) {
        jPanel2.setVisible(visible);

        if (getProtocolStep() != null) {
            if ((getProtocolStep().getSearchTopicInfos() == null)
                        || getProtocolStep().getSearchTopicInfos().isEmpty()) {
                jXHyperlink2.setVisible(false);
            } else {
                jXHyperlink2.setVisible(true);
                if (jPanel2.isVisible()) {
                    jXHyperlink2.setText(Integer.toString(getProtocolStep().getSearchTopicInfos().size())
                                + " Suchthemen verbergen");
                } else {
                    jXHyperlink2.setText(Integer.toString(getProtocolStep().getSearchTopicInfos().size())
                                + " Suchthemen anzeigen");
                }
            }
        }

        revalidate();
    }

    /**
     * DOCUMENT ME!
     *
     * @param   iconPath  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private static ImageIcon getImageIcon(final String iconPath) {
        if (!ICON_CACHE.containsKey(iconPath)) {
            ImageIcon imageIcon;
            try {
                imageIcon = new javax.swing.ImageIcon(SearchTopicsProtocolStepPanel.class.getResource(iconPath));
            } catch (final Exception ex) {
                imageIcon = new javax.swing.ImageIcon(SearchTopicsProtocolStepPanel.class.getResource(
                            "/de/cismet/cismap/navigatorplugin/metasearch/search.png"));
            }
            ICON_CACHE.put(iconPath, imageIcon);
        }
        return ICON_CACHE.get(iconPath);
    }

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    class TopicListCellRenderer extends DefaultListCellRenderer {

        //~ Methods ------------------------------------------------------------

        @Override
        public Component getListCellRendererComponent(final JList<?> list,
                final Object value,
                final int index,
                final boolean isSelected,
                final boolean cellHasFocus) {
            final MetaSearchProtocolStepSearchTopic topic = (MetaSearchProtocolStepSearchTopic)value;
            final JLabel component = (JLabel)super.getListCellRendererComponent(
                    list,
                    value,
                    index,
                    isSelected,
                    cellHasFocus);
            component.setIcon(getImageIcon(topic.getIconName()));
            component.setText(topic.getName());
            return component;
        }
    }
}
